### PR TITLE
fixed-number-parse-issue

### PR DESCRIPTION
**Pull request by Hakob**
#19 
I tried to fix the issue about number parsing. The actual case tested on this string when searching `test` word:

```dart
Test12345 Vlad Test Test Test 2345 TEST NEW MESSAGE
```

### CODE REVIEW

**Comment by Hakob** [comment]
@desconexo FYI

**Comment by desconexo** [comment]
thank you

**Comment by Hakob** [comment]
You're welcome))
Can you please tell me when it will be available in pub.dev as a package?

**Comment by desconexo** [comment]
I already sent it. Just need to wait a few hours for approval

**Comment by desconexo** [comment]
I believe it's already approved

**Pull request merged**
